---CREATE CATEGORY TABLE
CREATE TABLE IF NOT EXISTS category (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

---CREATE OUTPUT TABLE
CREATE TABLE IF NOT EXISTS output (
    id SERIAL NOT NULL PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    "date" DATE NOT NULL,
    category_id INTEGER NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OUTPUT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id)
);
-----------------

---CREATE INCOME TABLE
CREATE TABLE IF NOT EXISTS income (
    id SERIAL NOT NULL PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    description VARCHAR(255),
    date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
